name: Build MRS

on:
  push:
    paths:
      - "customize.txt"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download Mihomo
        shell: bash
        run: |
          VERSION=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | \
            grep '"tag_name":' | \
            head -1 | \
            cut -d '"' -f 4)

          echo "Mihomo version: $VERSION"

          wget -q \
            "https://github.com/MetaCubeX/mihomo/releases/download/${VERSION}/mihomo-linux-amd64-compatible-${VERSION}.gz" \
            -O mihomo.gz

          gunzip mihomo.gz
          chmod +x mihomo

      - name: Convert TXT to MRS
        run: |
          ./mihomo convert-ruleset domain yaml customize.txt customize.mrs

      - name: Upload MRS to Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload 1.0 customize.mrs --clobber
